// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message2Server.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Communication.Proto {

  /// <summary>Holder for reflection information generated from Message2Server.proto</summary>
  public static partial class Message2ServerReflection {

    #region Descriptor
    /// <summary>File descriptor for Message2Server.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Message2ServerReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRNZXNzYWdlMlNlcnZlci5wcm90bxIIUHJvdG9idWYaEU1lc3NhZ2VUeXBl",
            "LnByb3RvGhVNZXNzYWdlMkNsaWVudHMucHJvdG8i6gIKD01lc3NhZ2VUb1Nl",
            "cnZlchIqCgttZXNzYWdlVHlwZRgBIAEoDjIVLlByb3RvYnVmLk1lc3NhZ2VU",
            "eXBlEhAKCHBsYXllcklEGAIgASgDEg4KBnRlYW1JRBgDIAEoAxIqCgZwU2tp",
            "bGwYBCABKA4yGi5Qcm90b2J1Zi5QYXNzaXZlU2tpbGxUeXBlEioKB2FTa2ls",
            "bDEYBSABKA4yGS5Qcm90b2J1Zi5BY3RpdmVTa2lsbFR5cGUSKgoHYVNraWxs",
            "MhgGIAEoDjIZLlByb3RvYnVmLkFjdGl2ZVNraWxsVHlwZRIkCghwcm9wVHlw",
            "ZRgHIAEoDjISLlByb3RvYnVmLlByb3BUeXBlEhoKEnRpbWVJbk1pbGxpc2Vj",
            "b25kcxgIIAEoAxINCgVhbmdsZRgJIAEoARIPCgdnZW1TaXplGAogASgFEhIK",
            "ClRvUGxheWVySUQYCyABKAMSDwoHbWVzc2FnZRgMIAEoCUIWqgITQ29tbXVu",
            "aWNhdGlvbi5Qcm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Communication.Proto.MessageTypeReflection.Descriptor, global::Communication.Proto.Message2ClientsReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.Proto.MessageToServer), global::Communication.Proto.MessageToServer.Parser, new[]{ "MessageType", "PlayerID", "TeamID", "PSkill", "ASkill1", "ASkill2", "PropType", "TimeInMilliseconds", "Angle", "GemSize", "ToPlayerID", "Message" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MessageToServer : pb::IMessage<MessageToServer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageToServer> _parser = new pb::MessageParser<MessageToServer>(() => new MessageToServer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageToServer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.Proto.Message2ServerReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToServer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToServer(MessageToServer other) : this() {
      messageType_ = other.messageType_;
      playerID_ = other.playerID_;
      teamID_ = other.teamID_;
      pSkill_ = other.pSkill_;
      aSkill1_ = other.aSkill1_;
      aSkill2_ = other.aSkill2_;
      propType_ = other.propType_;
      timeInMilliseconds_ = other.timeInMilliseconds_;
      angle_ = other.angle_;
      gemSize_ = other.gemSize_;
      toPlayerID_ = other.toPlayerID_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToServer Clone() {
      return new MessageToServer(this);
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 1;
    private global::Communication.Proto.MessageType messageType_ = global::Communication.Proto.MessageType.AddPlayer;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 2;
    private long playerID_;
    /// <summary>
    ///消息发送者的playerID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "teamID" field.</summary>
    public const int TeamIDFieldNumber = 3;
    private long teamID_;
    /// <summary>
    ///消息发送者所在队伍的ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TeamID {
      get { return teamID_; }
      set {
        teamID_ = value;
      }
    }

    /// <summary>Field number for the "pSkill" field.</summary>
    public const int PSkillFieldNumber = 4;
    private global::Communication.Proto.PassiveSkillType pSkill_ = global::Communication.Proto.PassiveSkillType.NullPassiveSkillType;
    /// <summary>
    ///AddPlayer时添加的被动技能，下面是添加的两个主动技能。
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.PassiveSkillType PSkill {
      get { return pSkill_; }
      set {
        pSkill_ = value;
      }
    }

    /// <summary>Field number for the "aSkill1" field.</summary>
    public const int ASkill1FieldNumber = 5;
    private global::Communication.Proto.ActiveSkillType aSkill1_ = global::Communication.Proto.ActiveSkillType.NullActiveSkillType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.ActiveSkillType ASkill1 {
      get { return aSkill1_; }
      set {
        aSkill1_ = value;
      }
    }

    /// <summary>Field number for the "aSkill2" field.</summary>
    public const int ASkill2FieldNumber = 6;
    private global::Communication.Proto.ActiveSkillType aSkill2_ = global::Communication.Proto.ActiveSkillType.NullActiveSkillType;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.ActiveSkillType ASkill2 {
      get { return aSkill2_; }
      set {
        aSkill2_ = value;
      }
    }

    /// <summary>Field number for the "propType" field.</summary>
    public const int PropTypeFieldNumber = 7;
    private global::Communication.Proto.PropType propType_ = global::Communication.Proto.PropType.NullPropType;
    /// <summary>
    ///messageType为Pick时要捡起的道具类型
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.PropType PropType {
      get { return propType_; }
      set {
        propType_ = value;
      }
    }

    /// <summary>Field number for the "timeInMilliseconds" field.</summary>
    public const int TimeInMillisecondsFieldNumber = 8;
    private long timeInMilliseconds_;
    /// <summary>
    ///时间参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TimeInMilliseconds {
      get { return timeInMilliseconds_; }
      set {
        timeInMilliseconds_ = value;
      }
    }

    /// <summary>Field number for the "angle" field.</summary>
    public const int AngleFieldNumber = 9;
    private double angle_;
    /// <summary>
    ///角度参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Angle {
      get { return angle_; }
      set {
        angle_ = value;
      }
    }

    /// <summary>Field number for the "gemSize" field.</summary>
    public const int GemSizeFieldNumber = 10;
    private int gemSize_;
    /// <summary>
    ///宝石量参数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int GemSize {
      get { return gemSize_; }
      set {
        gemSize_ = value;
      }
    }

    /// <summary>Field number for the "ToPlayerID" field.</summary>
    public const int ToPlayerIDFieldNumber = 11;
    private long toPlayerID_;
    /// <summary>
    ///当messageType为Send时有效，为发送对象的ID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long ToPlayerID {
      get { return toPlayerID_; }
      set {
        toPlayerID_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 12;
    private string message_ = "";
    /// <summary>
    ///当messageType为Send时有效，为发送的消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageToServer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageToServer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MessageType != other.MessageType) return false;
      if (PlayerID != other.PlayerID) return false;
      if (TeamID != other.TeamID) return false;
      if (PSkill != other.PSkill) return false;
      if (ASkill1 != other.ASkill1) return false;
      if (ASkill2 != other.ASkill2) return false;
      if (PropType != other.PropType) return false;
      if (TimeInMilliseconds != other.TimeInMilliseconds) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Angle, other.Angle)) return false;
      if (GemSize != other.GemSize) return false;
      if (ToPlayerID != other.ToPlayerID) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) hash ^= MessageType.GetHashCode();
      if (PlayerID != 0L) hash ^= PlayerID.GetHashCode();
      if (TeamID != 0L) hash ^= TeamID.GetHashCode();
      if (PSkill != global::Communication.Proto.PassiveSkillType.NullPassiveSkillType) hash ^= PSkill.GetHashCode();
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) hash ^= ASkill1.GetHashCode();
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) hash ^= ASkill2.GetHashCode();
      if (PropType != global::Communication.Proto.PropType.NullPropType) hash ^= PropType.GetHashCode();
      if (TimeInMilliseconds != 0L) hash ^= TimeInMilliseconds.GetHashCode();
      if (Angle != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Angle);
      if (GemSize != 0) hash ^= GemSize.GetHashCode();
      if (ToPlayerID != 0L) hash ^= ToPlayerID.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (PlayerID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerID);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TeamID);
      }
      if (PSkill != global::Communication.Proto.PassiveSkillType.NullPassiveSkillType) {
        output.WriteRawTag(32);
        output.WriteEnum((int) PSkill);
      }
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) ASkill1);
      }
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        output.WriteRawTag(48);
        output.WriteEnum((int) ASkill2);
      }
      if (PropType != global::Communication.Proto.PropType.NullPropType) {
        output.WriteRawTag(56);
        output.WriteEnum((int) PropType);
      }
      if (TimeInMilliseconds != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(TimeInMilliseconds);
      }
      if (Angle != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Angle);
      }
      if (GemSize != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(GemSize);
      }
      if (ToPlayerID != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(ToPlayerID);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        output.WriteRawTag(8);
        output.WriteEnum((int) MessageType);
      }
      if (PlayerID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(PlayerID);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TeamID);
      }
      if (PSkill != global::Communication.Proto.PassiveSkillType.NullPassiveSkillType) {
        output.WriteRawTag(32);
        output.WriteEnum((int) PSkill);
      }
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        output.WriteRawTag(40);
        output.WriteEnum((int) ASkill1);
      }
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        output.WriteRawTag(48);
        output.WriteEnum((int) ASkill2);
      }
      if (PropType != global::Communication.Proto.PropType.NullPropType) {
        output.WriteRawTag(56);
        output.WriteEnum((int) PropType);
      }
      if (TimeInMilliseconds != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(TimeInMilliseconds);
      }
      if (Angle != 0D) {
        output.WriteRawTag(73);
        output.WriteDouble(Angle);
      }
      if (GemSize != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(GemSize);
      }
      if (ToPlayerID != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(ToPlayerID);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(98);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (PlayerID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerID);
      }
      if (TeamID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TeamID);
      }
      if (PSkill != global::Communication.Proto.PassiveSkillType.NullPassiveSkillType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PSkill);
      }
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ASkill1);
      }
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ASkill2);
      }
      if (PropType != global::Communication.Proto.PropType.NullPropType) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PropType);
      }
      if (TimeInMilliseconds != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimeInMilliseconds);
      }
      if (Angle != 0D) {
        size += 1 + 8;
      }
      if (GemSize != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(GemSize);
      }
      if (ToPlayerID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(ToPlayerID);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageToServer other) {
      if (other == null) {
        return;
      }
      if (other.MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        MessageType = other.MessageType;
      }
      if (other.PlayerID != 0L) {
        PlayerID = other.PlayerID;
      }
      if (other.TeamID != 0L) {
        TeamID = other.TeamID;
      }
      if (other.PSkill != global::Communication.Proto.PassiveSkillType.NullPassiveSkillType) {
        PSkill = other.PSkill;
      }
      if (other.ASkill1 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        ASkill1 = other.ASkill1;
      }
      if (other.ASkill2 != global::Communication.Proto.ActiveSkillType.NullActiveSkillType) {
        ASkill2 = other.ASkill2;
      }
      if (other.PropType != global::Communication.Proto.PropType.NullPropType) {
        PropType = other.PropType;
      }
      if (other.TimeInMilliseconds != 0L) {
        TimeInMilliseconds = other.TimeInMilliseconds;
      }
      if (other.Angle != 0D) {
        Angle = other.Angle;
      }
      if (other.GemSize != 0) {
        GemSize = other.GemSize;
      }
      if (other.ToPlayerID != 0L) {
        ToPlayerID = other.ToPlayerID;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MessageType = (global::Communication.Proto.MessageType) input.ReadEnum();
            break;
          }
          case 16: {
            PlayerID = input.ReadInt64();
            break;
          }
          case 24: {
            TeamID = input.ReadInt64();
            break;
          }
          case 32: {
            PSkill = (global::Communication.Proto.PassiveSkillType) input.ReadEnum();
            break;
          }
          case 40: {
            ASkill1 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 48: {
            ASkill2 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 56: {
            PropType = (global::Communication.Proto.PropType) input.ReadEnum();
            break;
          }
          case 64: {
            TimeInMilliseconds = input.ReadInt64();
            break;
          }
          case 73: {
            Angle = input.ReadDouble();
            break;
          }
          case 80: {
            GemSize = input.ReadInt32();
            break;
          }
          case 88: {
            ToPlayerID = input.ReadInt64();
            break;
          }
          case 98: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MessageType = (global::Communication.Proto.MessageType) input.ReadEnum();
            break;
          }
          case 16: {
            PlayerID = input.ReadInt64();
            break;
          }
          case 24: {
            TeamID = input.ReadInt64();
            break;
          }
          case 32: {
            PSkill = (global::Communication.Proto.PassiveSkillType) input.ReadEnum();
            break;
          }
          case 40: {
            ASkill1 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 48: {
            ASkill2 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 56: {
            PropType = (global::Communication.Proto.PropType) input.ReadEnum();
            break;
          }
          case 64: {
            TimeInMilliseconds = input.ReadInt64();
            break;
          }
          case 73: {
            Angle = input.ReadDouble();
            break;
          }
          case 80: {
            GemSize = input.ReadInt32();
            break;
          }
          case 88: {
            ToPlayerID = input.ReadInt64();
            break;
          }
          case 98: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
