// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Message2Clients.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Communication.Proto {

  /// <summary>Holder for reflection information generated from Message2Clients.proto</summary>
  public static partial class Message2ClientsReflection {

    #region Descriptor
    /// <summary>File descriptor for Message2Clients.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static Message2ClientsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChVNZXNzYWdlMkNsaWVudHMucHJvdG8SCFByb3RvYnVmGhFNZXNzYWdlVHlw",
            "ZS5wcm90byLkBAoLR2FtZU9iakluZm8SKgoLZ2FtZU9ialR5cGUYASABKA4y",
            "FS5Qcm90b2J1Zi5HYW1lT2JqVHlwZRIMCgRndWlkGAIgASgDEgkKAXgYAyAB",
            "KAUSCQoBeRgEIAEoBRIXCg9mYWNpbmdEaXJlY3Rpb24YBSABKAESEQoJbW92",
            "ZVNwZWVkGAYgASgFEg8KB2Nhbk1vdmUYByABKAgSEAoIaXNNb3ZpbmcYCCAB",
            "KAgSJgoJc2hhcGVUeXBlGAkgASgOMhMuUHJvdG9idWYuU2hhcGVUeXBlEg4K",
            "BnJhZGl1cxgKIAEoBRIOCgZ0ZWFtSUQYCyABKAMSCwoDYmFwGAwgASgFEhEK",
            "CWJvb21SYW5nZRgNIAEoBRIkCghwcm9wVHlwZRgOIAEoDjISLlByb3RvYnVm",
            "LlByb3BUeXBlEg4KBmlzTGFpZBgPIAEoCBIPCgdpc0R5aW5nGBAgASgIEgoK",
            "AkNEGBEgASgFEhQKDG1heEJ1bGxldE51bRgSIAEoBRIRCglidWxsZXROdW0Y",
            "EyABKAUSDQoFbWF4SHAYFCABKAUSCgoCaHAYFSABKAUSDwoHbGlmZU51bRgW",
            "IAEoBRIqCgZwU2tpbGwYFyABKA4yGi5Qcm90b2J1Zi5QYXNzaXZlU2tpbGxU",
            "eXBlEioKB2FTa2lsbDEYGCABKA4yGS5Qcm90b2J1Zi5BY3RpdmVTa2lsbFR5",
            "cGUSKgoHYVNraWxsMhgZIAEoDjIZLlByb3RvYnVmLkFjdGl2ZVNraWxsVHlw",
            "ZRIiCgVwbGFjZRgaIAEoDjITLlByb3RvYnVmLlBsYWNlVHlwZSKBAQoSTWVz",
            "c2FnZVRvT25lQ2xpZW50EhAKCHBsYXllcklEGAEgASgDEg4KBnRlYW1JRBgC",
            "IAEoAxIqCgttZXNzYWdlVHlwZRgDIAEoDjIVLlByb3RvYnVmLk1lc3NhZ2VU",
            "eXBlEgwKBGd1aWQYBCABKAMSDwoHbWVzc2FnZRgFIAEoCSKoAgoPTWVzc2Fn",
            "ZVRvQ2xpZW50EhAKCHBsYXllcklEGAEgASgDEg4KBnRlYW1JRBgCIAEoAxIq",
            "CgttZXNzYWdlVHlwZRgDIAEoDjIVLlByb3RvYnVmLk1lc3NhZ2VUeXBlEicK",
            "CHNlbGZJbmZvGAQgASgLMhUuUHJvdG9idWYuR2FtZU9iakluZm8SEQoJdGVh",
            "bVNjb3JlGAUgASgFEicKCGdhbWVPYmpzGAYgAygLMhUuUHJvdG9idWYuR2Ft",
            "ZU9iakluZm8SOwoLUGxheWVyR1VJRHMYByADKAsyJi5Qcm90b2J1Zi5NZXNz",
            "YWdlVG9DbGllbnQuT25lVGVhbUdVSURzGiUKDE9uZVRlYW1HVUlEcxIVCg10",
            "ZWFtbWF0ZUdVSURzGAEgAygDKmwKC0dhbWVPYmpUeXBlEg0KCUNoYXJhY3Rl",
            "chAAEggKBFdhbGwQARIICgRQcm9wEAISCgoGQnVsbGV0EAMSDgoKQmlydGhQ",
            "b2ludBAEEhMKD091dE9mQm91bmRCbG9jaxAFEgkKBUdyYXNzEAYqSgoJUGxh",
            "Y2VUeXBlEgoKBkdyb3VuZBAAEgoKBkdyYXNzMRABEgoKBkdyYXNzMhACEgoK",
            "BkdyYXNzMxADEg0KCUludmlzaWJsZRAEKpQBCghQcm9wVHlwZRIICgROdWxs",
            "EAASDgoKQWNjZWxlcmF0ZRABEgoKBnBsdXNBUBACEgsKB21pbnVzQ0QQAxIJ",
            "CgVhZGRIUBAEEgoKBlNoaWVsZBAFEgsKB2FkZExJRkUQBhIJCgVTcGVhchAH",
            "Eg4KCkRlY2VsZXJhdGUQCBILCgdtaW51c0FQEAkSCQoFYWRkQ0QQCiojCglT",
            "aGFwZVR5cGUSCgoGQ2lyY2xlEAASCgoGU3F1YXJlEAEqYAoQUGFzc2l2ZVNr",
            "aWxsVHlwZRILCgdQU2tpbGwwEAASCwoHUFNraWxsMRABEgsKB1BTa2lsbDIQ",
            "AhILCgdQU2tpbGwzEAMSCwoHUFNraWxsNBAEEgsKB1BTa2lsbDUQBSpfCg9B",
            "Y3RpdmVTa2lsbFR5cGUSCwoHQVNraWxsMBAAEgsKB0FTa2lsbDEQARILCgdB",
            "U2tpbGwyEAISCwoHQVNraWxsMxADEgsKB0FTa2lsbDQQBBILCgdBU2tpbGw1",
            "EAUqJgoKQnVsbGV0VHlwZRILCgdCdWxsZXQwEAASCwoHQnVsbGV0MRABQhaq",
            "AhNDb21tdW5pY2F0aW9uLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Communication.Proto.MessageTypeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Communication.Proto.GameObjType), typeof(global::Communication.Proto.PlaceType), typeof(global::Communication.Proto.PropType), typeof(global::Communication.Proto.ShapeType), typeof(global::Communication.Proto.PassiveSkillType), typeof(global::Communication.Proto.ActiveSkillType), typeof(global::Communication.Proto.BulletType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.Proto.GameObjInfo), global::Communication.Proto.GameObjInfo.Parser, new[]{ "GameObjType", "Guid", "X", "Y", "FacingDirection", "MoveSpeed", "CanMove", "IsMoving", "ShapeType", "Radius", "TeamID", "Bap", "BoomRange", "PropType", "IsLaid", "IsDying", "CD", "MaxBulletNum", "BulletNum", "MaxHp", "Hp", "LifeNum", "PSkill", "ASkill1", "ASkill2", "Place" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.Proto.MessageToOneClient), global::Communication.Proto.MessageToOneClient.Parser, new[]{ "PlayerID", "TeamID", "MessageType", "Guid", "Message" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Communication.Proto.MessageToClient), global::Communication.Proto.MessageToClient.Parser, new[]{ "PlayerID", "TeamID", "MessageType", "SelfInfo", "TeamScore", "GameObjs", "PlayerGUIDs" }, null, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Communication.Proto.MessageToClient.Types.OneTeamGUIDs), global::Communication.Proto.MessageToClient.Types.OneTeamGUIDs.Parser, new[]{ "TeammateGUIDs" }, null, null, null, null)})
          }));
    }
    #endregion

  }
  #region Enums
  public enum GameObjType {
    [pbr::OriginalName("Character")] Character = 0,
    [pbr::OriginalName("Wall")] Wall = 1,
    [pbr::OriginalName("Prop")] Prop = 2,
    [pbr::OriginalName("Bullet")] Bullet = 3,
    [pbr::OriginalName("BirthPoint")] BirthPoint = 4,
    [pbr::OriginalName("OutOfBoundBlock")] OutOfBoundBlock = 5,
    [pbr::OriginalName("Grass")] Grass = 6,
  }

  /// <summary>
  ///角色可见属性的枚举，包括：Ground（外围）0，Grass1、2、3，以及角色技能带来的隐身4
  /// </summary>
  public enum PlaceType {
    [pbr::OriginalName("Ground")] Ground = 0,
    [pbr::OriginalName("Grass1")] Grass1 = 1,
    [pbr::OriginalName("Grass2")] Grass2 = 2,
    [pbr::OriginalName("Grass3")] Grass3 = 3,
    [pbr::OriginalName("Invisible")] Invisible = 4,
  }

  /// <summary>
  ///道具类型，此为编写时的临时名称，具体道具名称可以待主题确定后更改
  /// </summary>
  public enum PropType {
    [pbr::OriginalName("Null")] Null = 0,
    [pbr::OriginalName("Accelerate")] Accelerate = 1,
    [pbr::OriginalName("plusAP")] PlusAp = 2,
    [pbr::OriginalName("minusCD")] MinusCd = 3,
    [pbr::OriginalName("addHP")] AddHp = 4,
    [pbr::OriginalName("Shield")] Shield = 5,
    [pbr::OriginalName("addLIFE")] AddLife = 6,
    [pbr::OriginalName("Spear")] Spear = 7,
    [pbr::OriginalName("Decelerate")] Decelerate = 8,
    [pbr::OriginalName("minusAP")] MinusAp = 9,
    [pbr::OriginalName("addCD")] AddCd = 10,
  }

  public enum ShapeType {
    /// <summary>
    ///仍然，子弹和人物为圆形，格子为方形
    /// </summary>
    [pbr::OriginalName("Circle")] Circle = 0,
    [pbr::OriginalName("Square")] Square = 1,
  }

  public enum PassiveSkillType {
    [pbr::OriginalName("PSkill0")] Pskill0 = 0,
    [pbr::OriginalName("PSkill1")] Pskill1 = 1,
    [pbr::OriginalName("PSkill2")] Pskill2 = 2,
    [pbr::OriginalName("PSkill3")] Pskill3 = 3,
    [pbr::OriginalName("PSkill4")] Pskill4 = 4,
    [pbr::OriginalName("PSkill5")] Pskill5 = 5,
  }

  public enum ActiveSkillType {
    [pbr::OriginalName("ASkill0")] Askill0 = 0,
    [pbr::OriginalName("ASkill1")] Askill1 = 1,
    [pbr::OriginalName("ASkill2")] Askill2 = 2,
    [pbr::OriginalName("ASkill3")] Askill3 = 3,
    [pbr::OriginalName("ASkill4")] Askill4 = 4,
    [pbr::OriginalName("ASkill5")] Askill5 = 5,
  }

  public enum BulletType {
    /// <summary>
    ///普通子弹
    /// </summary>
    [pbr::OriginalName("Bullet0")] Bullet0 = 0,
    /// <summary>
    ///爆弾
    /// </summary>
    [pbr::OriginalName("Bullet1")] Bullet1 = 1,
  }

  #endregion

  #region Messages
  public sealed partial class GameObjInfo : pb::IMessage<GameObjInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<GameObjInfo> _parser = new pb::MessageParser<GameObjInfo>(() => new GameObjInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<GameObjInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.Proto.Message2ClientsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameObjInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameObjInfo(GameObjInfo other) : this() {
      gameObjType_ = other.gameObjType_;
      guid_ = other.guid_;
      x_ = other.x_;
      y_ = other.y_;
      facingDirection_ = other.facingDirection_;
      moveSpeed_ = other.moveSpeed_;
      canMove_ = other.canMove_;
      isMoving_ = other.isMoving_;
      shapeType_ = other.shapeType_;
      radius_ = other.radius_;
      teamID_ = other.teamID_;
      bap_ = other.bap_;
      boomRange_ = other.boomRange_;
      propType_ = other.propType_;
      isLaid_ = other.isLaid_;
      isDying_ = other.isDying_;
      cD_ = other.cD_;
      maxBulletNum_ = other.maxBulletNum_;
      bulletNum_ = other.bulletNum_;
      maxHp_ = other.maxHp_;
      hp_ = other.hp_;
      lifeNum_ = other.lifeNum_;
      pSkill_ = other.pSkill_;
      aSkill1_ = other.aSkill1_;
      aSkill2_ = other.aSkill2_;
      place_ = other.place_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public GameObjInfo Clone() {
      return new GameObjInfo(this);
    }

    /// <summary>Field number for the "gameObjType" field.</summary>
    public const int GameObjTypeFieldNumber = 1;
    private global::Communication.Proto.GameObjType gameObjType_ = global::Communication.Proto.GameObjType.Character;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.GameObjType GameObjType {
      get { return gameObjType_; }
      set {
        gameObjType_ = value;
      }
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 2;
    private long guid_;
    /// <summary>
    ///以下当gameObjType为任意值时均时有效
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Guid {
      get { return guid_; }
      set {
        guid_ = value;
      }
    }

    /// <summary>Field number for the "x" field.</summary>
    public const int XFieldNumber = 3;
    private int x_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int X {
      get { return x_; }
      set {
        x_ = value;
      }
    }

    /// <summary>Field number for the "y" field.</summary>
    public const int YFieldNumber = 4;
    private int y_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Y {
      get { return y_; }
      set {
        y_ = value;
      }
    }

    /// <summary>Field number for the "facingDirection" field.</summary>
    public const int FacingDirectionFieldNumber = 5;
    private double facingDirection_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double FacingDirection {
      get { return facingDirection_; }
      set {
        facingDirection_ = value;
      }
    }

    /// <summary>Field number for the "moveSpeed" field.</summary>
    public const int MoveSpeedFieldNumber = 6;
    private int moveSpeed_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MoveSpeed {
      get { return moveSpeed_; }
      set {
        moveSpeed_ = value;
      }
    }

    /// <summary>Field number for the "canMove" field.</summary>
    public const int CanMoveFieldNumber = 7;
    private bool canMove_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool CanMove {
      get { return canMove_; }
      set {
        canMove_ = value;
      }
    }

    /// <summary>Field number for the "isMoving" field.</summary>
    public const int IsMovingFieldNumber = 8;
    private bool isMoving_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsMoving {
      get { return isMoving_; }
      set {
        isMoving_ = value;
      }
    }

    /// <summary>Field number for the "shapeType" field.</summary>
    public const int ShapeTypeFieldNumber = 9;
    private global::Communication.Proto.ShapeType shapeType_ = global::Communication.Proto.ShapeType.Circle;
    /// <summary>
    ///形状
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.ShapeType ShapeType {
      get { return shapeType_; }
      set {
        shapeType_ = value;
      }
    }

    /// <summary>Field number for the "radius" field.</summary>
    public const int RadiusFieldNumber = 10;
    private int radius_;
    /// <summary>
    ///圆形物体的半径或正方形内切圆半径
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Radius {
      get { return radius_; }
      set {
        radius_ = value;
      }
    }

    /// <summary>Field number for the "teamID" field.</summary>
    public const int TeamIDFieldNumber = 11;
    private long teamID_;
    /// <summary>
    ///以下当gameObjType为Character、Prop和Bullet时才有效
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TeamID {
      get { return teamID_; }
      set {
        teamID_ = value;
      }
    }

    /// <summary>Field number for the "bap" field.</summary>
    public const int BapFieldNumber = 12;
    private int bap_;
    /// <summary>
    ///以下当gameObjType为Bullet时才有效
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Bap {
      get { return bap_; }
      set {
        bap_ = value;
      }
    }

    /// <summary>Field number for the "boomRange" field.</summary>
    public const int BoomRangeFieldNumber = 13;
    private int boomRange_;
    /// <summary>
    ///子弹爆炸范围
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BoomRange {
      get { return boomRange_; }
      set {
        boomRange_ = value;
      }
    }

    /// <summary>Field number for the "propType" field.</summary>
    public const int PropTypeFieldNumber = 14;
    private global::Communication.Proto.PropType propType_ = global::Communication.Proto.PropType.Null;
    /// <summary>
    ///以下当gameObjType为Character和Prop时有效
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.PropType PropType {
      get { return propType_; }
      set {
        propType_ = value;
      }
    }

    /// <summary>Field number for the "isLaid" field.</summary>
    public const int IsLaidFieldNumber = 15;
    private bool isLaid_;
    /// <summary>
    ///以下仅当gameObjType为Prop时有效
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsLaid {
      get { return isLaid_; }
      set {
        isLaid_ = value;
      }
    }

    /// <summary>Field number for the "isDying" field.</summary>
    public const int IsDyingFieldNumber = 16;
    private bool isDying_;
    /// <summary>
    ///以下仅当gameObjType为Character时有效
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsDying {
      get { return isDying_; }
      set {
        isDying_ = value;
      }
    }

    /// <summary>Field number for the "CD" field.</summary>
    public const int CDFieldNumber = 17;
    private int cD_;
    /// <summary>
    ///回复子弹速度，并非技能CD
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CD {
      get { return cD_; }
      set {
        cD_ = value;
      }
    }

    /// <summary>Field number for the "maxBulletNum" field.</summary>
    public const int MaxBulletNumFieldNumber = 18;
    private int maxBulletNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxBulletNum {
      get { return maxBulletNum_; }
      set {
        maxBulletNum_ = value;
      }
    }

    /// <summary>Field number for the "bulletNum" field.</summary>
    public const int BulletNumFieldNumber = 19;
    private int bulletNum_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int BulletNum {
      get { return bulletNum_; }
      set {
        bulletNum_ = value;
      }
    }

    /// <summary>Field number for the "maxHp" field.</summary>
    public const int MaxHpFieldNumber = 20;
    private int maxHp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxHp {
      get { return maxHp_; }
      set {
        maxHp_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 21;
    private int hp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "lifeNum" field.</summary>
    public const int LifeNumFieldNumber = 22;
    private int lifeNum_;
    /// <summary>
    ///第几条命
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LifeNum {
      get { return lifeNum_; }
      set {
        lifeNum_ = value;
      }
    }

    /// <summary>Field number for the "pSkill" field.</summary>
    public const int PSkillFieldNumber = 23;
    private global::Communication.Proto.PassiveSkillType pSkill_ = global::Communication.Proto.PassiveSkillType.Pskill0;
    /// <summary>
    ///被动技能池
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.PassiveSkillType PSkill {
      get { return pSkill_; }
      set {
        pSkill_ = value;
      }
    }

    /// <summary>Field number for the "aSkill1" field.</summary>
    public const int ASkill1FieldNumber = 24;
    private global::Communication.Proto.ActiveSkillType aSkill1_ = global::Communication.Proto.ActiveSkillType.Askill0;
    /// <summary>
    ///主动1
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.ActiveSkillType ASkill1 {
      get { return aSkill1_; }
      set {
        aSkill1_ = value;
      }
    }

    /// <summary>Field number for the "aSkill2" field.</summary>
    public const int ASkill2FieldNumber = 25;
    private global::Communication.Proto.ActiveSkillType aSkill2_ = global::Communication.Proto.ActiveSkillType.Askill0;
    /// <summary>
    ///主动2
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.ActiveSkillType ASkill2 {
      get { return aSkill2_; }
      set {
        aSkill2_ = value;
      }
    }

    /// <summary>Field number for the "place" field.</summary>
    public const int PlaceFieldNumber = 26;
    private global::Communication.Proto.PlaceType place_ = global::Communication.Proto.PlaceType.Ground;
    /// <summary>
    ///角色位置状态，是否可见
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.PlaceType Place {
      get { return place_; }
      set {
        place_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as GameObjInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(GameObjInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (GameObjType != other.GameObjType) return false;
      if (Guid != other.Guid) return false;
      if (X != other.X) return false;
      if (Y != other.Y) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(FacingDirection, other.FacingDirection)) return false;
      if (MoveSpeed != other.MoveSpeed) return false;
      if (CanMove != other.CanMove) return false;
      if (IsMoving != other.IsMoving) return false;
      if (ShapeType != other.ShapeType) return false;
      if (Radius != other.Radius) return false;
      if (TeamID != other.TeamID) return false;
      if (Bap != other.Bap) return false;
      if (BoomRange != other.BoomRange) return false;
      if (PropType != other.PropType) return false;
      if (IsLaid != other.IsLaid) return false;
      if (IsDying != other.IsDying) return false;
      if (CD != other.CD) return false;
      if (MaxBulletNum != other.MaxBulletNum) return false;
      if (BulletNum != other.BulletNum) return false;
      if (MaxHp != other.MaxHp) return false;
      if (Hp != other.Hp) return false;
      if (LifeNum != other.LifeNum) return false;
      if (PSkill != other.PSkill) return false;
      if (ASkill1 != other.ASkill1) return false;
      if (ASkill2 != other.ASkill2) return false;
      if (Place != other.Place) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (GameObjType != global::Communication.Proto.GameObjType.Character) hash ^= GameObjType.GetHashCode();
      if (Guid != 0L) hash ^= Guid.GetHashCode();
      if (X != 0) hash ^= X.GetHashCode();
      if (Y != 0) hash ^= Y.GetHashCode();
      if (FacingDirection != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(FacingDirection);
      if (MoveSpeed != 0) hash ^= MoveSpeed.GetHashCode();
      if (CanMove != false) hash ^= CanMove.GetHashCode();
      if (IsMoving != false) hash ^= IsMoving.GetHashCode();
      if (ShapeType != global::Communication.Proto.ShapeType.Circle) hash ^= ShapeType.GetHashCode();
      if (Radius != 0) hash ^= Radius.GetHashCode();
      if (TeamID != 0L) hash ^= TeamID.GetHashCode();
      if (Bap != 0) hash ^= Bap.GetHashCode();
      if (BoomRange != 0) hash ^= BoomRange.GetHashCode();
      if (PropType != global::Communication.Proto.PropType.Null) hash ^= PropType.GetHashCode();
      if (IsLaid != false) hash ^= IsLaid.GetHashCode();
      if (IsDying != false) hash ^= IsDying.GetHashCode();
      if (CD != 0) hash ^= CD.GetHashCode();
      if (MaxBulletNum != 0) hash ^= MaxBulletNum.GetHashCode();
      if (BulletNum != 0) hash ^= BulletNum.GetHashCode();
      if (MaxHp != 0) hash ^= MaxHp.GetHashCode();
      if (Hp != 0) hash ^= Hp.GetHashCode();
      if (LifeNum != 0) hash ^= LifeNum.GetHashCode();
      if (PSkill != global::Communication.Proto.PassiveSkillType.Pskill0) hash ^= PSkill.GetHashCode();
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.Askill0) hash ^= ASkill1.GetHashCode();
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.Askill0) hash ^= ASkill2.GetHashCode();
      if (Place != global::Communication.Proto.PlaceType.Ground) hash ^= Place.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (GameObjType != global::Communication.Proto.GameObjType.Character) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GameObjType);
      }
      if (Guid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Guid);
      }
      if (X != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Y);
      }
      if (FacingDirection != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(FacingDirection);
      }
      if (MoveSpeed != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MoveSpeed);
      }
      if (CanMove != false) {
        output.WriteRawTag(56);
        output.WriteBool(CanMove);
      }
      if (IsMoving != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsMoving);
      }
      if (ShapeType != global::Communication.Proto.ShapeType.Circle) {
        output.WriteRawTag(72);
        output.WriteEnum((int) ShapeType);
      }
      if (Radius != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Radius);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(TeamID);
      }
      if (Bap != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Bap);
      }
      if (BoomRange != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(BoomRange);
      }
      if (PropType != global::Communication.Proto.PropType.Null) {
        output.WriteRawTag(112);
        output.WriteEnum((int) PropType);
      }
      if (IsLaid != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsLaid);
      }
      if (IsDying != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(IsDying);
      }
      if (CD != 0) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(CD);
      }
      if (MaxBulletNum != 0) {
        output.WriteRawTag(144, 1);
        output.WriteInt32(MaxBulletNum);
      }
      if (BulletNum != 0) {
        output.WriteRawTag(152, 1);
        output.WriteInt32(BulletNum);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(160, 1);
        output.WriteInt32(MaxHp);
      }
      if (Hp != 0) {
        output.WriteRawTag(168, 1);
        output.WriteInt32(Hp);
      }
      if (LifeNum != 0) {
        output.WriteRawTag(176, 1);
        output.WriteInt32(LifeNum);
      }
      if (PSkill != global::Communication.Proto.PassiveSkillType.Pskill0) {
        output.WriteRawTag(184, 1);
        output.WriteEnum((int) PSkill);
      }
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.Askill0) {
        output.WriteRawTag(192, 1);
        output.WriteEnum((int) ASkill1);
      }
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.Askill0) {
        output.WriteRawTag(200, 1);
        output.WriteEnum((int) ASkill2);
      }
      if (Place != global::Communication.Proto.PlaceType.Ground) {
        output.WriteRawTag(208, 1);
        output.WriteEnum((int) Place);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (GameObjType != global::Communication.Proto.GameObjType.Character) {
        output.WriteRawTag(8);
        output.WriteEnum((int) GameObjType);
      }
      if (Guid != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Guid);
      }
      if (X != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(X);
      }
      if (Y != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Y);
      }
      if (FacingDirection != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(FacingDirection);
      }
      if (MoveSpeed != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(MoveSpeed);
      }
      if (CanMove != false) {
        output.WriteRawTag(56);
        output.WriteBool(CanMove);
      }
      if (IsMoving != false) {
        output.WriteRawTag(64);
        output.WriteBool(IsMoving);
      }
      if (ShapeType != global::Communication.Proto.ShapeType.Circle) {
        output.WriteRawTag(72);
        output.WriteEnum((int) ShapeType);
      }
      if (Radius != 0) {
        output.WriteRawTag(80);
        output.WriteInt32(Radius);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(TeamID);
      }
      if (Bap != 0) {
        output.WriteRawTag(96);
        output.WriteInt32(Bap);
      }
      if (BoomRange != 0) {
        output.WriteRawTag(104);
        output.WriteInt32(BoomRange);
      }
      if (PropType != global::Communication.Proto.PropType.Null) {
        output.WriteRawTag(112);
        output.WriteEnum((int) PropType);
      }
      if (IsLaid != false) {
        output.WriteRawTag(120);
        output.WriteBool(IsLaid);
      }
      if (IsDying != false) {
        output.WriteRawTag(128, 1);
        output.WriteBool(IsDying);
      }
      if (CD != 0) {
        output.WriteRawTag(136, 1);
        output.WriteInt32(CD);
      }
      if (MaxBulletNum != 0) {
        output.WriteRawTag(144, 1);
        output.WriteInt32(MaxBulletNum);
      }
      if (BulletNum != 0) {
        output.WriteRawTag(152, 1);
        output.WriteInt32(BulletNum);
      }
      if (MaxHp != 0) {
        output.WriteRawTag(160, 1);
        output.WriteInt32(MaxHp);
      }
      if (Hp != 0) {
        output.WriteRawTag(168, 1);
        output.WriteInt32(Hp);
      }
      if (LifeNum != 0) {
        output.WriteRawTag(176, 1);
        output.WriteInt32(LifeNum);
      }
      if (PSkill != global::Communication.Proto.PassiveSkillType.Pskill0) {
        output.WriteRawTag(184, 1);
        output.WriteEnum((int) PSkill);
      }
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.Askill0) {
        output.WriteRawTag(192, 1);
        output.WriteEnum((int) ASkill1);
      }
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.Askill0) {
        output.WriteRawTag(200, 1);
        output.WriteEnum((int) ASkill2);
      }
      if (Place != global::Communication.Proto.PlaceType.Ground) {
        output.WriteRawTag(208, 1);
        output.WriteEnum((int) Place);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (GameObjType != global::Communication.Proto.GameObjType.Character) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) GameObjType);
      }
      if (Guid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Guid);
      }
      if (X != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(X);
      }
      if (Y != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Y);
      }
      if (FacingDirection != 0D) {
        size += 1 + 8;
      }
      if (MoveSpeed != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MoveSpeed);
      }
      if (CanMove != false) {
        size += 1 + 1;
      }
      if (IsMoving != false) {
        size += 1 + 1;
      }
      if (ShapeType != global::Communication.Proto.ShapeType.Circle) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ShapeType);
      }
      if (Radius != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Radius);
      }
      if (TeamID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TeamID);
      }
      if (Bap != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Bap);
      }
      if (BoomRange != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(BoomRange);
      }
      if (PropType != global::Communication.Proto.PropType.Null) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) PropType);
      }
      if (IsLaid != false) {
        size += 1 + 1;
      }
      if (IsDying != false) {
        size += 2 + 1;
      }
      if (CD != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(CD);
      }
      if (MaxBulletNum != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(MaxBulletNum);
      }
      if (BulletNum != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(BulletNum);
      }
      if (MaxHp != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(MaxHp);
      }
      if (Hp != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(Hp);
      }
      if (LifeNum != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(LifeNum);
      }
      if (PSkill != global::Communication.Proto.PassiveSkillType.Pskill0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) PSkill);
      }
      if (ASkill1 != global::Communication.Proto.ActiveSkillType.Askill0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ASkill1);
      }
      if (ASkill2 != global::Communication.Proto.ActiveSkillType.Askill0) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) ASkill2);
      }
      if (Place != global::Communication.Proto.PlaceType.Ground) {
        size += 2 + pb::CodedOutputStream.ComputeEnumSize((int) Place);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(GameObjInfo other) {
      if (other == null) {
        return;
      }
      if (other.GameObjType != global::Communication.Proto.GameObjType.Character) {
        GameObjType = other.GameObjType;
      }
      if (other.Guid != 0L) {
        Guid = other.Guid;
      }
      if (other.X != 0) {
        X = other.X;
      }
      if (other.Y != 0) {
        Y = other.Y;
      }
      if (other.FacingDirection != 0D) {
        FacingDirection = other.FacingDirection;
      }
      if (other.MoveSpeed != 0) {
        MoveSpeed = other.MoveSpeed;
      }
      if (other.CanMove != false) {
        CanMove = other.CanMove;
      }
      if (other.IsMoving != false) {
        IsMoving = other.IsMoving;
      }
      if (other.ShapeType != global::Communication.Proto.ShapeType.Circle) {
        ShapeType = other.ShapeType;
      }
      if (other.Radius != 0) {
        Radius = other.Radius;
      }
      if (other.TeamID != 0L) {
        TeamID = other.TeamID;
      }
      if (other.Bap != 0) {
        Bap = other.Bap;
      }
      if (other.BoomRange != 0) {
        BoomRange = other.BoomRange;
      }
      if (other.PropType != global::Communication.Proto.PropType.Null) {
        PropType = other.PropType;
      }
      if (other.IsLaid != false) {
        IsLaid = other.IsLaid;
      }
      if (other.IsDying != false) {
        IsDying = other.IsDying;
      }
      if (other.CD != 0) {
        CD = other.CD;
      }
      if (other.MaxBulletNum != 0) {
        MaxBulletNum = other.MaxBulletNum;
      }
      if (other.BulletNum != 0) {
        BulletNum = other.BulletNum;
      }
      if (other.MaxHp != 0) {
        MaxHp = other.MaxHp;
      }
      if (other.Hp != 0) {
        Hp = other.Hp;
      }
      if (other.LifeNum != 0) {
        LifeNum = other.LifeNum;
      }
      if (other.PSkill != global::Communication.Proto.PassiveSkillType.Pskill0) {
        PSkill = other.PSkill;
      }
      if (other.ASkill1 != global::Communication.Proto.ActiveSkillType.Askill0) {
        ASkill1 = other.ASkill1;
      }
      if (other.ASkill2 != global::Communication.Proto.ActiveSkillType.Askill0) {
        ASkill2 = other.ASkill2;
      }
      if (other.Place != global::Communication.Proto.PlaceType.Ground) {
        Place = other.Place;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            GameObjType = (global::Communication.Proto.GameObjType) input.ReadEnum();
            break;
          }
          case 16: {
            Guid = input.ReadInt64();
            break;
          }
          case 24: {
            X = input.ReadInt32();
            break;
          }
          case 32: {
            Y = input.ReadInt32();
            break;
          }
          case 41: {
            FacingDirection = input.ReadDouble();
            break;
          }
          case 48: {
            MoveSpeed = input.ReadInt32();
            break;
          }
          case 56: {
            CanMove = input.ReadBool();
            break;
          }
          case 64: {
            IsMoving = input.ReadBool();
            break;
          }
          case 72: {
            ShapeType = (global::Communication.Proto.ShapeType) input.ReadEnum();
            break;
          }
          case 80: {
            Radius = input.ReadInt32();
            break;
          }
          case 88: {
            TeamID = input.ReadInt64();
            break;
          }
          case 96: {
            Bap = input.ReadInt32();
            break;
          }
          case 104: {
            BoomRange = input.ReadInt32();
            break;
          }
          case 112: {
            PropType = (global::Communication.Proto.PropType) input.ReadEnum();
            break;
          }
          case 120: {
            IsLaid = input.ReadBool();
            break;
          }
          case 128: {
            IsDying = input.ReadBool();
            break;
          }
          case 136: {
            CD = input.ReadInt32();
            break;
          }
          case 144: {
            MaxBulletNum = input.ReadInt32();
            break;
          }
          case 152: {
            BulletNum = input.ReadInt32();
            break;
          }
          case 160: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 168: {
            Hp = input.ReadInt32();
            break;
          }
          case 176: {
            LifeNum = input.ReadInt32();
            break;
          }
          case 184: {
            PSkill = (global::Communication.Proto.PassiveSkillType) input.ReadEnum();
            break;
          }
          case 192: {
            ASkill1 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 200: {
            ASkill2 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 208: {
            Place = (global::Communication.Proto.PlaceType) input.ReadEnum();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            GameObjType = (global::Communication.Proto.GameObjType) input.ReadEnum();
            break;
          }
          case 16: {
            Guid = input.ReadInt64();
            break;
          }
          case 24: {
            X = input.ReadInt32();
            break;
          }
          case 32: {
            Y = input.ReadInt32();
            break;
          }
          case 41: {
            FacingDirection = input.ReadDouble();
            break;
          }
          case 48: {
            MoveSpeed = input.ReadInt32();
            break;
          }
          case 56: {
            CanMove = input.ReadBool();
            break;
          }
          case 64: {
            IsMoving = input.ReadBool();
            break;
          }
          case 72: {
            ShapeType = (global::Communication.Proto.ShapeType) input.ReadEnum();
            break;
          }
          case 80: {
            Radius = input.ReadInt32();
            break;
          }
          case 88: {
            TeamID = input.ReadInt64();
            break;
          }
          case 96: {
            Bap = input.ReadInt32();
            break;
          }
          case 104: {
            BoomRange = input.ReadInt32();
            break;
          }
          case 112: {
            PropType = (global::Communication.Proto.PropType) input.ReadEnum();
            break;
          }
          case 120: {
            IsLaid = input.ReadBool();
            break;
          }
          case 128: {
            IsDying = input.ReadBool();
            break;
          }
          case 136: {
            CD = input.ReadInt32();
            break;
          }
          case 144: {
            MaxBulletNum = input.ReadInt32();
            break;
          }
          case 152: {
            BulletNum = input.ReadInt32();
            break;
          }
          case 160: {
            MaxHp = input.ReadInt32();
            break;
          }
          case 168: {
            Hp = input.ReadInt32();
            break;
          }
          case 176: {
            LifeNum = input.ReadInt32();
            break;
          }
          case 184: {
            PSkill = (global::Communication.Proto.PassiveSkillType) input.ReadEnum();
            break;
          }
          case 192: {
            ASkill1 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 200: {
            ASkill2 = (global::Communication.Proto.ActiveSkillType) input.ReadEnum();
            break;
          }
          case 208: {
            Place = (global::Communication.Proto.PlaceType) input.ReadEnum();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///发送单个信息时
  /// </summary>
  public sealed partial class MessageToOneClient : pb::IMessage<MessageToOneClient>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageToOneClient> _parser = new pb::MessageParser<MessageToOneClient>(() => new MessageToOneClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageToOneClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.Proto.Message2ClientsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToOneClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToOneClient(MessageToOneClient other) : this() {
      playerID_ = other.playerID_;
      teamID_ = other.teamID_;
      messageType_ = other.messageType_;
      guid_ = other.guid_;
      message_ = other.message_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToOneClient Clone() {
      return new MessageToOneClient(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private long playerID_;
    /// <summary>
    ///指明发送给谁
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "teamID" field.</summary>
    public const int TeamIDFieldNumber = 2;
    private long teamID_;
    /// <summary>
    ///指明发送给谁
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TeamID {
      get { return teamID_; }
      set {
        teamID_ = value;
      }
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 3;
    private global::Communication.Proto.MessageType messageType_ = global::Communication.Proto.MessageType.AddPlayer;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "guid" field.</summary>
    public const int GuidFieldNumber = 4;
    private long guid_;
    /// <summary>
    ///自己的guid
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Guid {
      get { return guid_; }
      set {
        guid_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 5;
    private string message_ = "";
    /// <summary>
    ///如果 messageType 为 Send，则为要发送的消息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageToOneClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageToOneClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if (TeamID != other.TeamID) return false;
      if (MessageType != other.MessageType) return false;
      if (Guid != other.Guid) return false;
      if (Message != other.Message) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0L) hash ^= PlayerID.GetHashCode();
      if (TeamID != 0L) hash ^= TeamID.GetHashCode();
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) hash ^= MessageType.GetHashCode();
      if (Guid != 0L) hash ^= Guid.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerID);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TeamID);
      }
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MessageType);
      }
      if (Guid != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Guid);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerID);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TeamID);
      }
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MessageType);
      }
      if (Guid != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Guid);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(Message);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerID);
      }
      if (TeamID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TeamID);
      }
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (Guid != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Guid);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageToOneClient other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0L) {
        PlayerID = other.PlayerID;
      }
      if (other.TeamID != 0L) {
        TeamID = other.TeamID;
      }
      if (other.MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        MessageType = other.MessageType;
      }
      if (other.Guid != 0L) {
        Guid = other.Guid;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerID = input.ReadInt64();
            break;
          }
          case 16: {
            TeamID = input.ReadInt64();
            break;
          }
          case 24: {
            MessageType = (global::Communication.Proto.MessageType) input.ReadEnum();
            break;
          }
          case 32: {
            Guid = input.ReadInt64();
            break;
          }
          case 42: {
            Message = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerID = input.ReadInt64();
            break;
          }
          case 16: {
            TeamID = input.ReadInt64();
            break;
          }
          case 24: {
            MessageType = (global::Communication.Proto.MessageType) input.ReadEnum();
            break;
          }
          case 32: {
            Guid = input.ReadInt64();
            break;
          }
          case 42: {
            Message = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  /// <summary>
  ///发送全局信息时
  /// </summary>
  public sealed partial class MessageToClient : pb::IMessage<MessageToClient>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MessageToClient> _parser = new pb::MessageParser<MessageToClient>(() => new MessageToClient());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MessageToClient> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Communication.Proto.Message2ClientsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToClient() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToClient(MessageToClient other) : this() {
      playerID_ = other.playerID_;
      teamID_ = other.teamID_;
      messageType_ = other.messageType_;
      selfInfo_ = other.selfInfo_ != null ? other.selfInfo_.Clone() : null;
      teamScore_ = other.teamScore_;
      gameObjs_ = other.gameObjs_.Clone();
      playerGUIDs_ = other.playerGUIDs_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MessageToClient Clone() {
      return new MessageToClient(this);
    }

    /// <summary>Field number for the "playerID" field.</summary>
    public const int PlayerIDFieldNumber = 1;
    private long playerID_;
    /// <summary>
    ///指明发送给谁
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long PlayerID {
      get { return playerID_; }
      set {
        playerID_ = value;
      }
    }

    /// <summary>Field number for the "teamID" field.</summary>
    public const int TeamIDFieldNumber = 2;
    private long teamID_;
    /// <summary>
    ///指明发送给谁
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TeamID {
      get { return teamID_; }
      set {
        teamID_ = value;
      }
    }

    /// <summary>Field number for the "messageType" field.</summary>
    public const int MessageTypeFieldNumber = 3;
    private global::Communication.Proto.MessageType messageType_ = global::Communication.Proto.MessageType.AddPlayer;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.MessageType MessageType {
      get { return messageType_; }
      set {
        messageType_ = value;
      }
    }

    /// <summary>Field number for the "selfInfo" field.</summary>
    public const int SelfInfoFieldNumber = 4;
    private global::Communication.Proto.GameObjInfo selfInfo_;
    /// <summary>
    ///自己的个人信息
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Communication.Proto.GameObjInfo SelfInfo {
      get { return selfInfo_; }
      set {
        selfInfo_ = value;
      }
    }

    /// <summary>Field number for the "teamScore" field.</summary>
    public const int TeamScoreFieldNumber = 5;
    private int teamScore_;
    /// <summary>
    ///本队伍的分数
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TeamScore {
      get { return teamScore_; }
      set {
        teamScore_ = value;
      }
    }

    /// <summary>Field number for the "gameObjs" field.</summary>
    public const int GameObjsFieldNumber = 6;
    private static readonly pb::FieldCodec<global::Communication.Proto.GameObjInfo> _repeated_gameObjs_codec
        = pb::FieldCodec.ForMessage(50, global::Communication.Proto.GameObjInfo.Parser);
    private readonly pbc::RepeatedField<global::Communication.Proto.GameObjInfo> gameObjs_ = new pbc::RepeatedField<global::Communication.Proto.GameObjInfo>();
    /// <summary>
    ///当前地图上的所有对象
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Communication.Proto.GameObjInfo> GameObjs {
      get { return gameObjs_; }
    }

    /// <summary>Field number for the "PlayerGUIDs" field.</summary>
    public const int PlayerGUIDsFieldNumber = 7;
    private static readonly pb::FieldCodec<global::Communication.Proto.MessageToClient.Types.OneTeamGUIDs> _repeated_playerGUIDs_codec
        = pb::FieldCodec.ForMessage(58, global::Communication.Proto.MessageToClient.Types.OneTeamGUIDs.Parser);
    private readonly pbc::RepeatedField<global::Communication.Proto.MessageToClient.Types.OneTeamGUIDs> playerGUIDs_ = new pbc::RepeatedField<global::Communication.Proto.MessageToClient.Types.OneTeamGUIDs>();
    /// <summary>
    ///所有玩家的GUID，第一维的 0、1、2…… 分别为队伍编号，每个队伍的0、1、2、……元素分别为playerID为0、1、2、……的玩家的GUID，若不存在该玩家，则为Constant::Constant::InvalidGUID
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Communication.Proto.MessageToClient.Types.OneTeamGUIDs> PlayerGUIDs {
      get { return playerGUIDs_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MessageToClient);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MessageToClient other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PlayerID != other.PlayerID) return false;
      if (TeamID != other.TeamID) return false;
      if (MessageType != other.MessageType) return false;
      if (!object.Equals(SelfInfo, other.SelfInfo)) return false;
      if (TeamScore != other.TeamScore) return false;
      if(!gameObjs_.Equals(other.gameObjs_)) return false;
      if(!playerGUIDs_.Equals(other.playerGUIDs_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PlayerID != 0L) hash ^= PlayerID.GetHashCode();
      if (TeamID != 0L) hash ^= TeamID.GetHashCode();
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) hash ^= MessageType.GetHashCode();
      if (selfInfo_ != null) hash ^= SelfInfo.GetHashCode();
      if (TeamScore != 0) hash ^= TeamScore.GetHashCode();
      hash ^= gameObjs_.GetHashCode();
      hash ^= playerGUIDs_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PlayerID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerID);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TeamID);
      }
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MessageType);
      }
      if (selfInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SelfInfo);
      }
      if (TeamScore != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(TeamScore);
      }
      gameObjs_.WriteTo(output, _repeated_gameObjs_codec);
      playerGUIDs_.WriteTo(output, _repeated_playerGUIDs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PlayerID != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(PlayerID);
      }
      if (TeamID != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TeamID);
      }
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        output.WriteRawTag(24);
        output.WriteEnum((int) MessageType);
      }
      if (selfInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SelfInfo);
      }
      if (TeamScore != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(TeamScore);
      }
      gameObjs_.WriteTo(ref output, _repeated_gameObjs_codec);
      playerGUIDs_.WriteTo(ref output, _repeated_playerGUIDs_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PlayerID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(PlayerID);
      }
      if (TeamID != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TeamID);
      }
      if (MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) MessageType);
      }
      if (selfInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SelfInfo);
      }
      if (TeamScore != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TeamScore);
      }
      size += gameObjs_.CalculateSize(_repeated_gameObjs_codec);
      size += playerGUIDs_.CalculateSize(_repeated_playerGUIDs_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MessageToClient other) {
      if (other == null) {
        return;
      }
      if (other.PlayerID != 0L) {
        PlayerID = other.PlayerID;
      }
      if (other.TeamID != 0L) {
        TeamID = other.TeamID;
      }
      if (other.MessageType != global::Communication.Proto.MessageType.AddPlayer) {
        MessageType = other.MessageType;
      }
      if (other.selfInfo_ != null) {
        if (selfInfo_ == null) {
          SelfInfo = new global::Communication.Proto.GameObjInfo();
        }
        SelfInfo.MergeFrom(other.SelfInfo);
      }
      if (other.TeamScore != 0) {
        TeamScore = other.TeamScore;
      }
      gameObjs_.Add(other.gameObjs_);
      playerGUIDs_.Add(other.playerGUIDs_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PlayerID = input.ReadInt64();
            break;
          }
          case 16: {
            TeamID = input.ReadInt64();
            break;
          }
          case 24: {
            MessageType = (global::Communication.Proto.MessageType) input.ReadEnum();
            break;
          }
          case 34: {
            if (selfInfo_ == null) {
              SelfInfo = new global::Communication.Proto.GameObjInfo();
            }
            input.ReadMessage(SelfInfo);
            break;
          }
          case 40: {
            TeamScore = input.ReadInt32();
            break;
          }
          case 50: {
            gameObjs_.AddEntriesFrom(input, _repeated_gameObjs_codec);
            break;
          }
          case 58: {
            playerGUIDs_.AddEntriesFrom(input, _repeated_playerGUIDs_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PlayerID = input.ReadInt64();
            break;
          }
          case 16: {
            TeamID = input.ReadInt64();
            break;
          }
          case 24: {
            MessageType = (global::Communication.Proto.MessageType) input.ReadEnum();
            break;
          }
          case 34: {
            if (selfInfo_ == null) {
              SelfInfo = new global::Communication.Proto.GameObjInfo();
            }
            input.ReadMessage(SelfInfo);
            break;
          }
          case 40: {
            TeamScore = input.ReadInt32();
            break;
          }
          case 50: {
            gameObjs_.AddEntriesFrom(ref input, _repeated_gameObjs_codec);
            break;
          }
          case 58: {
            playerGUIDs_.AddEntriesFrom(ref input, _repeated_playerGUIDs_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the MessageToClient message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public sealed partial class OneTeamGUIDs : pb::IMessage<OneTeamGUIDs>
      #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          , pb::IBufferMessage
      #endif
      {
        private static readonly pb::MessageParser<OneTeamGUIDs> _parser = new pb::MessageParser<OneTeamGUIDs>(() => new OneTeamGUIDs());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<OneTeamGUIDs> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Communication.Proto.MessageToClient.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OneTeamGUIDs() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OneTeamGUIDs(OneTeamGUIDs other) : this() {
          teammateGUIDs_ = other.teammateGUIDs_.Clone();
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public OneTeamGUIDs Clone() {
          return new OneTeamGUIDs(this);
        }

        /// <summary>Field number for the "teammateGUIDs" field.</summary>
        public const int TeammateGUIDsFieldNumber = 1;
        private static readonly pb::FieldCodec<long> _repeated_teammateGUIDs_codec
            = pb::FieldCodec.ForInt64(10);
        private readonly pbc::RepeatedField<long> teammateGUIDs_ = new pbc::RepeatedField<long>();
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public pbc::RepeatedField<long> TeammateGUIDs {
          get { return teammateGUIDs_; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other) {
          return Equals(other as OneTeamGUIDs);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(OneTeamGUIDs other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if(!teammateGUIDs_.Equals(other.teammateGUIDs_)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode() {
          int hash = 1;
          hash ^= teammateGUIDs_.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          output.WriteRawMessage(this);
        #else
          teammateGUIDs_.WriteTo(output, _repeated_teammateGUIDs_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
          teammateGUIDs_.WriteTo(ref output, _repeated_teammateGUIDs_codec);
          if (_unknownFields != null) {
            _unknownFields.WriteTo(ref output);
          }
        }
        #endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize() {
          int size = 0;
          size += teammateGUIDs_.CalculateSize(_repeated_teammateGUIDs_codec);
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(OneTeamGUIDs other) {
          if (other == null) {
            return;
          }
          teammateGUIDs_.Add(other.teammateGUIDs_);
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input) {
        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
          input.ReadRawMessage(this);
        #else
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10:
              case 8: {
                teammateGUIDs_.AddEntriesFrom(input, _repeated_teammateGUIDs_codec);
                break;
              }
            }
          }
        #endif
        }

        #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                break;
              case 10:
              case 8: {
                teammateGUIDs_.AddEntriesFrom(ref input, _repeated_teammateGUIDs_codec);
                break;
              }
            }
          }
        }
        #endif

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
