// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Communication.Proto {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIUHJvdG9idWYqhAIKC01lc3NhZ2VUeXBl",
            "Eg0KCUFkZFBsYXllchAAEggKBE1vdmUQARIKCgZBdHRhY2sQAhIICgRQaWNr",
            "EAMSCwoHVXNlUHJvcBAEEg0KCVRocm93UHJvcBAFEggKBFNlbmQQBhIRCg1J",
            "bnZhbGlkUGxheWVyEAcSDwoLVmFsaWRQbGF5ZXIQCBINCglTdGFydEdhbWUQ",
            "CRIKCgZHYW1pbmcQChILCgdFbmRHYW1lEAsSEgoOVXNlQ29tbW9uU2tpbGwQ",
            "DBIUChBVc2VVbHRpbWF0ZVNraWxsEA0SEAoMSW5pdGlhbExpemVkEA4SCgoG",
            "VXNlR2VtEA8SDAoIVGhyb3dHZW0QECqBAQoLR2FtZU9ialR5cGUSEwoPTnVs",
            "bEdhbWVPYmpUeXBlEAASDQoJQ2hhcmFjdGVyEAESCAoEV2FsbBACEggKBFBy",
            "b3AQAxIKCgZCdWxsZXQQBBIOCgpCaXJ0aFBvaW50EAUSEwoPT3V0T2ZCb3Vu",
            "ZEJsb2NrEAYSCQoFR3Jhc3MQByo2CglTaGFwZVR5cGUSEQoNTnVsbFNoYXBl",
            "VHlwZRAAEgoKBkNpcmNsZRABEgoKBlNxdWFyZRACKlsKCVBsYWNlVHlwZRIR",
            "Cg1OdWxsUGxhY2VUeXBlEAASCAoETGFuZBABEgoKBkdyYXNzMRACEgoKBkdy",
            "YXNzMhADEgoKBkdyYXNzMxAEEg0KCUludmlzaWJsZRAFKqIBCghQcm9wVHlw",
            "ZRIQCgxOdWxsUHJvcFR5cGUQABIJCgVhZGRIUBABEgkKBWFkZEFQEAISDAoI",
            "YWRkU3BlZWQQAxILCgdhZGRMSUZFEAQSCwoHbWludXNDRBAFEgcKA0dlbRAG",
            "EgoKBlNoaWVsZBAHEgkKBVNwZWFyEAgSDgoKbWludXNTcGVlZBAJEgsKB21p",
            "bnVzQVAQChIJCgVhZGRDRBALKpUBChBQYXNzaXZlU2tpbGxUeXBlEhgKFE51",
            "bGxQYXNzaXZlU2tpbGxUeXBlEAASFgoSUmVjb3ZlckFmdGVyQmF0dGxlEAES",
            "GwoXU3BlZWRVcFdoZW5MZWF2aW5nR3Jhc3MQAhILCgdWYW1waXJlEAMSCwoH",
            "UFNraWxsMxAEEgsKB1BTa2lsbDQQBRILCgdQU2tpbGw1EAYqjQEKD0FjdGl2",
            "ZVNraWxsVHlwZRIXChNOdWxsQWN0aXZlU2tpbGxUeXBlEAASEQoNQmVjb21l",
            "VmFtcGlyZRABEhIKDkJlY29tZUFzc2Fzc2luEAISEQoNTnVjbGVhcldlYXBv",
            "bhADEg0KCVN1cGVyRmFzdBAEEgsKB0FTa2lsbDQQBRILCgdBU2tpbGw1EAYq",
            "ZwoIQnVmZlR5cGUSEAoMTnVsbEJ1ZmZUeXBlEAASDQoJTW92ZVNwZWVkEAES",
            "BgoCQVAQAhIGCgJDRBADEgsKB0FkZExJRkUQBBIOCgpTaGllbGRCdWZmEAUS",
            "DQoJU3BlYXJCdWZmEAYqegoKQnVsbGV0VHlwZRISCg5OdWxsQnVsbGV0VHlw",
            "ZRAAEhEKDUNvbW1vbkJ1bGxldDEQARIRCg1Db21tb25CdWxsZXQyEAISEQoN",
            "Q29tbW9uQnVsbGV0MxADEhEKDUNvbW1vbkJ1bGxldDQQBBIMCghBdG9tQm9t",
            "YhAFQhaqAhNDb21tdW5pY2F0aW9uLlByb3RvYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Communication.Proto.MessageType), typeof(global::Communication.Proto.GameObjType), typeof(global::Communication.Proto.ShapeType), typeof(global::Communication.Proto.PlaceType), typeof(global::Communication.Proto.PropType), typeof(global::Communication.Proto.PassiveSkillType), typeof(global::Communication.Proto.ActiveSkillType), typeof(global::Communication.Proto.BuffType), typeof(global::Communication.Proto.BulletType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageType {
    [pbr::OriginalName("AddPlayer")] AddPlayer = 0,
    [pbr::OriginalName("Move")] Move = 1,
    /// <summary>
    ///注：所有人物都用子弹攻击
    /// </summary>
    [pbr::OriginalName("Attack")] Attack = 2,
    [pbr::OriginalName("Pick")] Pick = 3,
    [pbr::OriginalName("UseProp")] UseProp = 4,
    [pbr::OriginalName("ThrowProp")] ThrowProp = 5,
    [pbr::OriginalName("Send")] Send = 6,
    [pbr::OriginalName("InvalidPlayer")] InvalidPlayer = 7,
    [pbr::OriginalName("ValidPlayer")] ValidPlayer = 8,
    [pbr::OriginalName("StartGame")] StartGame = 9,
    [pbr::OriginalName("Gaming")] Gaming = 10,
    [pbr::OriginalName("EndGame")] EndGame = 11,
    /// <summary>
    ///使用CommonSkill
    /// </summary>
    [pbr::OriginalName("UseCommonSkill")] UseCommonSkill = 12,
    /// <summary>
    ///使用UltimateSkill。UltimateSkill极有可能不会有，即人物极有可能只有PassiveSkill和CommonSkill。
    /// </summary>
    [pbr::OriginalName("UseUltimateSkill")] UseUltimateSkill = 13,
    /// <summary>
    ///Server给Client发送初始化消息十分关键，因此这里用StartGame-MessageToInitialize-InitialLized三次握手确认该操作的成功。
    /// </summary>
    [pbr::OriginalName("InitialLized")] InitialLized = 14,
    [pbr::OriginalName("UseGem")] UseGem = 15,
    [pbr::OriginalName("ThrowGem")] ThrowGem = 16,
  }

  public enum GameObjType {
    [pbr::OriginalName("NullGameObjType")] NullGameObjType = 0,
    [pbr::OriginalName("Character")] Character = 1,
    [pbr::OriginalName("Wall")] Wall = 2,
    [pbr::OriginalName("Prop")] Prop = 3,
    [pbr::OriginalName("Bullet")] Bullet = 4,
    [pbr::OriginalName("BirthPoint")] BirthPoint = 5,
    [pbr::OriginalName("OutOfBoundBlock")] OutOfBoundBlock = 6,
    [pbr::OriginalName("Grass")] Grass = 7,
  }

  public enum ShapeType {
    [pbr::OriginalName("NullShapeType")] NullShapeType = 0,
    /// <summary>
    ///仍然，子弹和人物为圆形，格子为方形
    /// </summary>
    [pbr::OriginalName("Circle")] Circle = 1,
    [pbr::OriginalName("Square")] Square = 2,
  }

  public enum PlaceType {
    [pbr::OriginalName("NullPlaceType")] NullPlaceType = 0,
    [pbr::OriginalName("Land")] Land = 1,
    [pbr::OriginalName("Grass1")] Grass1 = 2,
    [pbr::OriginalName("Grass2")] Grass2 = 3,
    [pbr::OriginalName("Grass3")] Grass3 = 4,
    [pbr::OriginalName("Invisible")] Invisible = 5,
  }

  public enum PropType {
    [pbr::OriginalName("NullPropType")] NullPropType = 0,
    [pbr::OriginalName("addHP")] AddHp = 1,
    [pbr::OriginalName("addAP")] AddAp = 2,
    [pbr::OriginalName("addSpeed")] AddSpeed = 3,
    [pbr::OriginalName("addLIFE")] AddLife = 4,
    [pbr::OriginalName("minusCD")] MinusCd = 5,
    /// <summary>
    /// 新增：宝石
    /// </summary>
    [pbr::OriginalName("Gem")] Gem = 6,
    [pbr::OriginalName("Shield")] Shield = 7,
    [pbr::OriginalName("Spear")] Spear = 8,
    [pbr::OriginalName("minusSpeed")] MinusSpeed = 9,
    [pbr::OriginalName("minusAP")] MinusAp = 10,
    [pbr::OriginalName("addCD")] AddCd = 11,
  }

  public enum PassiveSkillType {
    [pbr::OriginalName("NullPassiveSkillType")] NullPassiveSkillType = 0,
    [pbr::OriginalName("RecoverAfterBattle")] RecoverAfterBattle = 1,
    [pbr::OriginalName("SpeedUpWhenLeavingGrass")] SpeedUpWhenLeavingGrass = 2,
    [pbr::OriginalName("Vampire")] Vampire = 3,
    [pbr::OriginalName("PSkill3")] Pskill3 = 4,
    [pbr::OriginalName("PSkill4")] Pskill4 = 5,
    [pbr::OriginalName("PSkill5")] Pskill5 = 6,
  }

  public enum ActiveSkillType {
    [pbr::OriginalName("NullActiveSkillType")] NullActiveSkillType = 0,
    [pbr::OriginalName("BecomeVampire")] BecomeVampire = 1,
    [pbr::OriginalName("BecomeAssassin")] BecomeAssassin = 2,
    [pbr::OriginalName("NuclearWeapon")] NuclearWeapon = 3,
    [pbr::OriginalName("SuperFast")] SuperFast = 4,
    [pbr::OriginalName("ASkill4")] Askill4 = 5,
    [pbr::OriginalName("ASkill5")] Askill5 = 6,
  }

  public enum BuffType {
    [pbr::OriginalName("NullBuffType")] NullBuffType = 0,
    [pbr::OriginalName("MoveSpeed")] MoveSpeed = 1,
    [pbr::OriginalName("AP")] Ap = 2,
    [pbr::OriginalName("CD")] Cd = 3,
    [pbr::OriginalName("AddLIFE")] AddLife = 4,
    [pbr::OriginalName("ShieldBuff")] ShieldBuff = 5,
    [pbr::OriginalName("SpearBuff")] SpearBuff = 6,
  }

  public enum BulletType {
    [pbr::OriginalName("NullBulletType")] NullBulletType = 0,
    [pbr::OriginalName("CommonBullet1")] CommonBullet1 = 1,
    [pbr::OriginalName("CommonBullet2")] CommonBullet2 = 2,
    [pbr::OriginalName("CommonBullet3")] CommonBullet3 = 3,
    [pbr::OriginalName("CommonBullet4")] CommonBullet4 = 4,
    [pbr::OriginalName("AtomBomb")] AtomBomb = 5,
  }

  #endregion

}

#endregion Designer generated code
