// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MessageType.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Communication.Proto {

  /// <summary>Holder for reflection information generated from MessageType.proto</summary>
  public static partial class MessageTypeReflection {

    #region Descriptor
    /// <summary>File descriptor for MessageType.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessageTypeReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChFNZXNzYWdlVHlwZS5wcm90bxIIUHJvdG9idWYq+wEKC01lc3NhZ2VUeXBl",
            "Eg0KCUFkZFBsYXllchAAEggKBE1vdmUQARIKCgZBdHRhY2sQAhIICgRQaWNr",
            "EAMSCwoHVXNlUHJvcBAEEg0KCVRocm93UHJvcBAFEggKBFNlbmQQBhIRCg1J",
            "bnZhbGlkUGxheWVyEAcSDwoLVmFsaWRQbGF5ZXIQCBINCglTdGFydEdhbWUQ",
            "CRIKCgZHYW1pbmcQChILCgdFbmRHYW1lEAsSEgoOVXNlQ29tbW9uU2tpbGwQ",
            "DBIUChBVc2VVbHRpbWF0ZVNraWxsEA0SCgoGVXNlR2VtEA4SDAoIVGhyb3dH",
            "ZW0QDxIHCgNNYXAQECqgAQoLR2FtZU9ialR5cGUSEwoPTnVsbEdhbWVPYmpU",
            "eXBlEAASDQoJQ2hhcmFjdGVyEAESCAoEV2FsbBACEggKBFByb3AQAxIKCgZC",
            "dWxsZXQQBBIOCgpCaXJ0aFBvaW50EAUSEwoPT3V0T2ZCb3VuZEJsb2NrEAYS",
            "CQoFR3Jhc3MQBxILCgdHZW1XZWxsEAgSEAoMQm9tYmVkQnVsbGV0EAkqNgoJ",
            "U2hhcGVUeXBlEhEKDU51bGxTaGFwZVR5cGUQABIKCgZDaXJjbGUQARIKCgZT",
            "cXVhcmUQAipMCglQbGFjZVR5cGUSEQoNTnVsbFBsYWNlVHlwZRAAEggKBExh",
            "bmQQARIKCgZHcmFzczEQAhIKCgZHcmFzczIQAxIKCgZHcmFzczMQBCpXCghQ",
            "cm9wVHlwZRIQCgxOdWxsUHJvcFR5cGUQABIMCghhZGRTcGVlZBABEgsKB2Fk",
            "ZExJRkUQAhIHCgNHZW0QAxIKCgZTaGllbGQQBBIJCgVTcGVhchAFKpUBChBQ",
            "YXNzaXZlU2tpbGxUeXBlEhgKFE51bGxQYXNzaXZlU2tpbGxUeXBlEAASFgoS",
            "UmVjb3ZlckFmdGVyQmF0dGxlEAESGwoXU3BlZWRVcFdoZW5MZWF2aW5nR3Jh",
            "c3MQAhILCgdWYW1waXJlEAMSCwoHUFNraWxsMxAEEgsKB1BTa2lsbDQQBRIL",
            "CgdQU2tpbGw1EAYqjQEKD0FjdGl2ZVNraWxsVHlwZRIXChNOdWxsQWN0aXZl",
            "U2tpbGxUeXBlEAASEQoNQmVjb21lVmFtcGlyZRABEhIKDkJlY29tZUFzc2Fz",
            "c2luEAISEQoNTnVjbGVhcldlYXBvbhADEg0KCVN1cGVyRmFzdBAEEgsKB0FT",
            "a2lsbDQQBRILCgdBU2tpbGw1EAYqZwoIQnVmZlR5cGUSEAoMTnVsbEJ1ZmZU",
            "eXBlEAASDQoJTW92ZVNwZWVkEAESBgoCQVAQAhIGCgJDRBADEgsKB0FkZExJ",
            "RkUQBBIOCgpTaGllbGRCdWZmEAUSDQoJU3BlYXJCdWZmEAYqdQoKQnVsbGV0",
            "VHlwZRISCg5OdWxsQnVsbGV0VHlwZRAAEg4KCkxpbmVCdWxsZXQQARIRCg1D",
            "b21tb25CdWxsZXQyEAISDgoKRmFzdEJ1bGxldBADEhIKDk9yZGluYXJ5QnVs",
            "bGV0EAQSDAoIQXRvbUJvbWIQBUIWqgITQ29tbXVuaWNhdGlvbi5Qcm90b2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Communication.Proto.MessageType), typeof(global::Communication.Proto.GameObjType), typeof(global::Communication.Proto.ShapeType), typeof(global::Communication.Proto.PlaceType), typeof(global::Communication.Proto.PropType), typeof(global::Communication.Proto.PassiveSkillType), typeof(global::Communication.Proto.ActiveSkillType), typeof(global::Communication.Proto.BuffType), typeof(global::Communication.Proto.BulletType), }, null, null));
    }
    #endregion

  }
  #region Enums
  public enum MessageType {
    [pbr::OriginalName("AddPlayer")] AddPlayer = 0,
    [pbr::OriginalName("Move")] Move = 1,
    /// <summary>
    ///注：所有人物都用子弹攻击
    /// </summary>
    [pbr::OriginalName("Attack")] Attack = 2,
    [pbr::OriginalName("Pick")] Pick = 3,
    [pbr::OriginalName("UseProp")] UseProp = 4,
    [pbr::OriginalName("ThrowProp")] ThrowProp = 5,
    [pbr::OriginalName("Send")] Send = 6,
    [pbr::OriginalName("InvalidPlayer")] InvalidPlayer = 7,
    [pbr::OriginalName("ValidPlayer")] ValidPlayer = 8,
    [pbr::OriginalName("StartGame")] StartGame = 9,
    [pbr::OriginalName("Gaming")] Gaming = 10,
    [pbr::OriginalName("EndGame")] EndGame = 11,
    /// <summary>
    ///使用CommonSkill
    /// </summary>
    [pbr::OriginalName("UseCommonSkill")] UseCommonSkill = 12,
    /// <summary>
    ///使用UltimateSkill。UltimateSkill极有可能不会有，即人物极有可能只有PassiveSkill和CommonSkill。
    /// </summary>
    [pbr::OriginalName("UseUltimateSkill")] UseUltimateSkill = 13,
    [pbr::OriginalName("UseGem")] UseGem = 14,
    [pbr::OriginalName("ThrowGem")] ThrowGem = 15,
    [pbr::OriginalName("Map")] Map = 16,
  }

  public enum GameObjType {
    [pbr::OriginalName("NullGameObjType")] NullGameObjType = 0,
    [pbr::OriginalName("Character")] Character = 1,
    [pbr::OriginalName("Wall")] Wall = 2,
    [pbr::OriginalName("Prop")] Prop = 3,
    [pbr::OriginalName("Bullet")] Bullet = 4,
    [pbr::OriginalName("BirthPoint")] BirthPoint = 5,
    [pbr::OriginalName("OutOfBoundBlock")] OutOfBoundBlock = 6,
    [pbr::OriginalName("Grass")] Grass = 7,
    [pbr::OriginalName("GemWell")] GemWell = 8,
    [pbr::OriginalName("BombedBullet")] BombedBullet = 9,
  }

  public enum ShapeType {
    [pbr::OriginalName("NullShapeType")] NullShapeType = 0,
    /// <summary>
    ///仍然，子弹和人物为圆形，格子为方形
    /// </summary>
    [pbr::OriginalName("Circle")] Circle = 1,
    [pbr::OriginalName("Square")] Square = 2,
  }

  public enum PlaceType {
    [pbr::OriginalName("NullPlaceType")] NullPlaceType = 0,
    [pbr::OriginalName("Land")] Land = 1,
    [pbr::OriginalName("Grass1")] Grass1 = 2,
    [pbr::OriginalName("Grass2")] Grass2 = 3,
    [pbr::OriginalName("Grass3")] Grass3 = 4,
  }

  public enum PropType {
    [pbr::OriginalName("NullPropType")] NullPropType = 0,
    /// <summary>
    /// 加速
    /// </summary>
    [pbr::OriginalName("addSpeed")] AddSpeed = 1,
    /// <summary>
    /// 多一条命
    /// </summary>
    [pbr::OriginalName("addLIFE")] AddLife = 2,
    /// <summary>
    /// 新增：宝石
    /// </summary>
    [pbr::OriginalName("Gem")] Gem = 3,
    /// <summary>
    /// 护盾
    /// </summary>
    [pbr::OriginalName("Shield")] Shield = 4,
    /// <summary>
    /// 破盾
    /// </summary>
    [pbr::OriginalName("Spear")] Spear = 5,
  }

  public enum PassiveSkillType {
    [pbr::OriginalName("NullPassiveSkillType")] NullPassiveSkillType = 0,
    [pbr::OriginalName("RecoverAfterBattle")] RecoverAfterBattle = 1,
    [pbr::OriginalName("SpeedUpWhenLeavingGrass")] SpeedUpWhenLeavingGrass = 2,
    [pbr::OriginalName("Vampire")] Vampire = 3,
    [pbr::OriginalName("PSkill3")] Pskill3 = 4,
    [pbr::OriginalName("PSkill4")] Pskill4 = 5,
    [pbr::OriginalName("PSkill5")] Pskill5 = 6,
  }

  public enum ActiveSkillType {
    [pbr::OriginalName("NullActiveSkillType")] NullActiveSkillType = 0,
    [pbr::OriginalName("BecomeVampire")] BecomeVampire = 1,
    [pbr::OriginalName("BecomeAssassin")] BecomeAssassin = 2,
    [pbr::OriginalName("NuclearWeapon")] NuclearWeapon = 3,
    [pbr::OriginalName("SuperFast")] SuperFast = 4,
    [pbr::OriginalName("ASkill4")] Askill4 = 5,
    [pbr::OriginalName("ASkill5")] Askill5 = 6,
  }

  public enum BuffType {
    [pbr::OriginalName("NullBuffType")] NullBuffType = 0,
    [pbr::OriginalName("MoveSpeed")] MoveSpeed = 1,
    [pbr::OriginalName("AP")] Ap = 2,
    [pbr::OriginalName("CD")] Cd = 3,
    [pbr::OriginalName("AddLIFE")] AddLife = 4,
    [pbr::OriginalName("ShieldBuff")] ShieldBuff = 5,
    [pbr::OriginalName("SpearBuff")] SpearBuff = 6,
  }

  public enum BulletType {
    [pbr::OriginalName("NullBulletType")] NullBulletType = 0,
    [pbr::OriginalName("LineBullet")] LineBullet = 1,
    [pbr::OriginalName("CommonBullet2")] CommonBullet2 = 2,
    [pbr::OriginalName("FastBullet")] FastBullet = 3,
    [pbr::OriginalName("OrdinaryBullet")] OrdinaryBullet = 4,
    [pbr::OriginalName("AtomBomb")] AtomBomb = 5,
  }

  #endregion

}

#endregion Designer generated code
