FROM ubuntu:18.04
Maintainer eesast.com
WORKDIR /usr/local
RUN mkdir /usr/local/mnt
RUN apt-get update && apt-get install --no-install-recommends -y gcc g++ make libprotobuf-dev wget curl ca-certificates cmake autoconf automake libtool curl unzip
COPY ./CAPI /usr/local/CAPI
COPY ./dependency/shell/compile.sh ./
RUN cd ./CAPI/protobuf && ./autogen.sh && ./configure && make && make install && ldconfig
RUN cd /usr/local && mkdir ./CAPI/lib && wget -O dependency.zip https://cloud.tsinghua.edu.cn/f/9257418fd0ed40049c00/?dl=1 && unzip dependency.zip && mv -f ./linux/a ./CAPI/lib && mv -f ./linux/so ./CAPI/lib
ENTRYPOINT ["bash", "compile.sh"]