FROM ubuntu:18.04
Maintainer eesast.com
WORKDIR /usr/local
RUN mkdir /usr/local/play && mkdir /usr/local/Server
RUN apt-get update && apt-get install --no-install-recommends -y gcc g++ make libprotobuf-dev wget curl ca-certificates
RUN wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm packages-microsoft-prod.deb
RUN apt-get update && apt-get install -y apt-transport-https && apt-get update && apt-get install -y aspnetcore-runtime-5.0
COPY ./Server/ ./usr/local/Server/
COPY ./dependency/shell/run.sh ./usr/local/
ENTRYPOINT ["dotnet", "./Server/Server.dll"]
CMD ["-p", "20000", "--teamCount", "2", "--playerCount", "4", "-t", "600", "--fileName", 'video']
ENTRYPOINT ["bash", "./usr/local/run.sh"]