FROM ubuntu:18.04
Maintainer eesast.com
WORKDIR /usr/local
RUN mkdir /usr/local/mnt
RUN apt-get update && apt-get install --no-install-recommends -y gcc g++ make libprotobuf-dev wget curl ca-certificates
RUN wget https://github.com/Kitware/CMake/releases/download/v3.22.3/cmake-3.22.3-Linux-x86_64.tar.gz --no-check-certificate \
	&& tar -zxvf cmake-3.22.3-Linux-x86_64.tar.gz && rm cmake-3.22.3-Linux-x86_64.tar.gz
ENV PATH=$PATH:/usr/local/cmake-3.22.3-Linux-x86_64/bin
COPY ./CAPI /usr/local/CAPI
RUN cd ./CAPI/protobuf && ./autogen.sh && ./configure && make && make install && ldconfig && cd ../..
RUN cp -f /usr/local/mnt/player.cpp ./API/src/AI.cpp
RUN cmake CMakeLists.txt && make